/**
 * Strategy Registry - Manages all registered reward strategies.
 *
 * The registry provides a central point for:
 * - Registering new strategies
 * - Looking up strategies by name
 * - Iterating over all registered strategies
 * - Managing the strategy collection
 * - Executing strategies for a given context
 *
 * Following the Registry Pattern (PoEAA), this allows for dynamic
 * strategy registration and discovery at runtime.
 */

import pino from 'pino';

import type { IRewardStrategy } from './reward-strategy.interface';
import type { RewardContext, Reward } from './reward.types';

/**
 * Result of executing strategies for a context.
 */
export interface StrategyExecutionResult {
  /** All rewards generated by applicable strategies */
  rewards: Reward[];
  /** Total XP to award (sum of all XP-type rewards) */
  totalXP: number;
  /** Total streak bonus XP (for display purposes) */
  totalStreakBonus: number;
  /** All badges to award (deduplicated by code) */
  badgesToAward: Array<{
    code: string;
    name: string;
    icon: string;
    description: string;
  }>;
  /** Strategy names that were executed */
  executedStrategies: string[];
}

/**
 * Registry for managing reward strategies.
 */
export class StrategyRegistry {
  private strategies = new Map<string, IRewardStrategy>();
  private readonly logger: pino.Logger;

  constructor(logger?: pino.Logger) {
    this.logger = logger ?? pino({ level: 'silent' });
  }

  /**
   * Register a strategy with the registry.
   *
   * @param strategy - The strategy to register
   * @throws Error if a strategy with the same name is already registered
   */
  register(strategy: IRewardStrategy): void {
    if (this.strategies.has(strategy.name)) {
      throw new Error(`Strategy with name "${strategy.name}" is already registered`);
    }
    this.strategies.set(strategy.name, strategy);
    this.logger.debug(`[StrategyRegistry] Registered strategy: ${strategy.name}`);
  }

  /**
   * Remove a strategy from the registry.
   *
   * @param name - The name of the strategy to remove
   * @returns true if the strategy was removed, false if it wasn't found
   */
  unregister(name: string): boolean {
    return this.strategies.delete(name);
  }

  /**
   * Get a strategy by name.
   *
   * @param name - The name of the strategy to find
   * @returns The strategy if found, undefined otherwise
   */
  findByName(name: string): IRewardStrategy | undefined {
    return this.strategies.get(name);
  }

  /**
   * Get all registered strategies.
   *
   * @returns Array of all registered strategies
   */
  getStrategies(): IRewardStrategy[] {
    return Array.from(this.strategies.values());
  }

  /**
   * Get the number of registered strategies.
   */
  get count(): number {
    return this.strategies.size;
  }

  /**
   * Check if a strategy with the given name is registered.
   *
   * @param name - The name to check
   */
  has(name: string): boolean {
    return this.strategies.has(name);
  }

  /**
   * Clear all registered strategies.
   */
  clear(): void {
    this.strategies.clear();
  }

  /**
   * Replace a strategy (for testing or dynamic updates).
   *
   * @param strategy - The strategy to replace with
   */
  replace(strategy: IRewardStrategy): void {
    if (!this.strategies.has(strategy.name)) {
      throw new Error(`Strategy "${strategy.name}" not found in registry`);
    }
    this.strategies.set(strategy.name, strategy);
  }

  /**
   * Execute all applicable strategies for the given context.
   *
   * Strategies are executed in registration order. Only strategies that return
   * true from `canApply` will have their rewards included.
   *
   * @param context - The context to evaluate
   * @returns Aggregated results from all applicable strategies
   */
  async execute(context: RewardContext): Promise<StrategyExecutionResult> {
    const rewards: Reward[] = [];
    const executedStrategies: string[] = [];
    const badgeMap = new Map<string, { name: string; icon: string; description: string }>();

    this.logger.debug(
      `[StrategyRegistry] Executing strategies for ${context.userId} on ${context.event.type}`,
    );

    for (const strategy of this.strategies.values()) {
      try {
        const canApply = await strategy.canApply(context);
        if (canApply) {
          this.logger.debug(`[StrategyRegistry] Strategy ${strategy.name} applies, getting reward`);
          const reward = await strategy.getReward(context);
          if (reward) {
            rewards.push(reward);
            executedStrategies.push(strategy.name);

            // Handle badge rewards (deduplicate by code)
            if (reward.type === 'BADGE' && reward.badgeCode) {
              if (!badgeMap.has(reward.badgeCode)) {
                badgeMap.set(reward.badgeCode, {
                  name: reward.badgeName ?? reward.badgeCode,
                  icon: reward.badgeIcon ?? '🏆',
                  description: reward.description,
                });
              }
            }
          }
        }
      } catch (error) {
        this.logger.error(
          { err: error },
          `[StrategyRegistry] Error executing strategy ${strategy.name}`,
        );
        // Continue with other strategies even if one fails
      }
    }

    // Calculate totals
    const totalXP = rewards
      .filter((r) => r.type === 'XP')
      .reduce((sum, r) => sum + (r.amount ?? 0), 0);

    const totalStreakBonus = rewards
      .filter((r) => r.type === 'STREAK_BONUS')
      .reduce((sum, r) => sum + (r.amount ?? 0), 0);

    return {
      rewards,
      totalXP,
      totalStreakBonus,
      badgesToAward: Array.from(badgeMap.entries()).map(([code, data]) => ({
        code,
        ...data,
      })),
      executedStrategies,
    };
  }
}

// Singleton instance for application-wide use
let registryInstance: StrategyRegistry | null = null;

/**
 * Get the global strategy registry instance.
 */
export function getStrategyRegistry(): StrategyRegistry {
  if (!registryInstance) {
    registryInstance = new StrategyRegistry();
  }
  return registryInstance;
}

/**
 * Reset the strategy registry (primarily for testing).
 */
export function resetStrategyRegistry(): void {
  if (registryInstance) {
    registryInstance.clear();
  }
  registryInstance = null;
}
